
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import java.awt.event.ItemEvent;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class KonversiSuhuForm extends javax.swing.JFrame {

    /**
     * Creates new form KonversiSuhuForm
     */
    public KonversiSuhuForm() {
        initComponents();
        
        // menambahkan ItemListener untuk setiap JRadioButton
        jRadioButton1.addItemListener(e -> {
            if (e.getStateChange() == ItemEvent.SELECTED) {
                lakukanKonversi();
            }
        });

        jRadioButton2.addItemListener(e -> {
            if (e.getStateChange() == ItemEvent.SELECTED) {
                lakukanKonversi();
            }
        });

        jRadioButton3.addItemListener(e -> {
            if (e.getStateChange() == ItemEvent.SELECTED) {
                lakukanKonversi();
            }
        });

        jRadioButton4.addItemListener(e -> {
            if (e.getStateChange() == ItemEvent.SELECTED) {
                lakukanKonversi();
            }
        });

        // menambahkan DocumentListener ke jTextField1
        jTextField1.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                lakukanKonversi();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                lakukanKonversi();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                lakukanKonversi();
            }
        });
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Konversi Suhu");
        setSize(new java.awt.Dimension(200, 2));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Aplikasi Konversi Suhu");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Masukkan Suhu");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Konversi ke ");

        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Suhu", "Celsius", "Fahrenheit", "Kelvin", "Reamur", " " }));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton1.setText("KONVERSI");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Celcius");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Fahrenheit");

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Kelvin");

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("Reamue");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Hasil Konversi");

        jTextField2.setEditable(false);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton2.setText("KELUAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(75, 75, 75))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton1)
                                    .addComponent(jRadioButton4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton3)
                                    .addComponent(jRadioButton2)))
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(81, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       try {
        // Ambil nilai suhu dari JTextField input
        double inputSuhu = Double.parseDouble(jTextField1.getText());
        double hasil = 0;

        // Ambil skala asal dari ComboBox
        String skalaAsal = jComboBox1.getSelectedItem().toString();

        // Tentukan skala tujuan dari RadioButton yang dipilih
        String skalaTujuan = "";
        if (jRadioButton1.isSelected()) {
            skalaTujuan = "Celsius";
        } else if (jRadioButton2.isSelected()) {
            skalaTujuan = "Fahrenheit";
        } else if (jRadioButton3.isSelected()) {
            skalaTujuan = "Kelvin";
        } else if (jRadioButton4.isSelected()) {
            skalaTujuan = "Reamur";
        }

        // Jika skala asal sama dengan skala tujuan, tampilkan langsung tanpa konversi
        if (skalaAsal.equals(skalaTujuan)) {
            jTextField2.setText(String.valueOf(inputSuhu));
            return; // Hentikan proses konversi di sini
        }

           // Konversi suhu berdasarkan skala asal dan tujuan
           switch (skalaAsal) {
               case "Celsius":
                   switch (skalaTujuan) {
                       case "Fahrenheit":
                           hasil = inputSuhu * 9 / 5 + 32;
                           break;
                       case "Kelvin":
                           hasil = inputSuhu + 273.15;
                           break;
                       case "Reamur":
                           hasil = inputSuhu * 4 / 5;
                           break;
                       default:
                           break;
                   }      break;
               case "Fahrenheit":
                   switch (skalaTujuan) {
                       case "Celsius":
                           hasil = (inputSuhu - 32) * 5 / 9;
                           break;
                       case "Kelvin":
                           hasil = (inputSuhu - 32) * 5 / 9 + 273.15;
                           break;
                       case "Reamur":
                           hasil = (inputSuhu - 32) * 4 / 9;
                           break;
                       default:
                           break;
                   }      break;
               case "Kelvin":
                   switch (skalaTujuan) {
                       case "Celsius":
                           hasil = inputSuhu - 273.15;
                           break;
                       case "Fahrenheit":
                           hasil = (inputSuhu - 273.15) * 9 / 5 + 32;
                           break;
                       case "Reamur":
                           hasil = (inputSuhu - 273.15) * 4 / 5;
                           break;
                       default:
                           break;
                   }      break;
               case "Reamur":
                   switch (skalaTujuan) {
                       case "Celsius":
                           hasil = inputSuhu * 5 / 4;
                           break;
                       case "Fahrenheit":
                           hasil = inputSuhu * 9 / 4 + 32;
                           break;
                       case "Kelvin":
                           hasil = inputSuhu * 5 / 4 + 273.15;
                           break;
                       default:
                           break;
                   }      break;
               default:
                   break;
           }

            // Tampilkan hasil konversi di JTextField hasil
            jTextField2.setText(String.valueOf(hasil));
        } catch (NumberFormatException e) {
            // Tampilkan pesan error jika input tidak valid
            JOptionPane.showMessageDialog(this, "Input tidak valid! Masukkan angka.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();  // Batalkan karakter jika bukan angka
        }
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
        jTextField1.setText("");
    }//GEN-LAST:event_jTextField1FocusGained

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int pilihan = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin keluar?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
    
        if (pilihan == JOptionPane.YES_OPTION) {
            System.exit(0);  // Keluar dari aplikasi
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void lakukanKonversi() {
    try {
        
        double input = Double.parseDouble(jTextField1.getText());
        String skalaAsal = jComboBox1.getSelectedItem().toString();
        double hasil = 0;

        // Pilih skala tujuan berdasarkan JRadioButton yang dipilih
        if (jRadioButton1.isSelected()) {
            hasil = Celsius(input, skalaAsal);
        } else if (jRadioButton2.isSelected()) {
            hasil = Fahrenheit(input, skalaAsal);
        } else if (jRadioButton3.isSelected()) {
            hasil = Kelvin(input, skalaAsal);
        } else if (jRadioButton4.isSelected()) {
            hasil = Reamur(input, skalaAsal);
        }

        jTextField2.setText(String.format("%.2f", hasil));
        } catch (NumberFormatException e) {
            jTextField2.setText("Input tidak valid");
        }
    }
    
    private double Celsius(double input, String skalaAsal) {
        switch (skalaAsal) {
            case "Fahrenheit":
                return (input - 32) * 5 / 9;
            case "Kelvin":
                return input - 273.15;
            case "Reamur":
                return input * 5 / 4;
            default:
                return input; // Jika skala asal adalah Celsius
        }
    }

    private double Fahrenheit(double input, String skalaAsal) {
        switch (skalaAsal) {
            case "Celsius":
                return input * 9 / 5 + 32;
            case "Kelvin":
                return (input - 32) * 5 / 9 + 273.15;
            case "Reamur":
                return (input - 32) * 4 / 9;
            default:
                return input; // Jika skala asal adalah Fahrenheit
        }
    }

    private double Kelvin(double input, String skalaAsal) {
        switch (skalaAsal) {
            case "Celsius":
                return input + 273.15;
            case "Fahrenheit":
                return (input - 273.15) * 9 / 5 + 32;
            case "Reamur":
                return (input - 273.15) * 4 / 5;
            default:
                return input; // Jika skala asal adalah Kelvin
        }
    }

    private double Reamur(double input, String skalaAsal) {
        switch (skalaAsal) {
            case "Celsius":
                return input * 4 / 5;
            case "Fahrenheit":
                return input * 9 / 4 + 32;
            case "Kelvin":
                return input * 5 / 4 + 273.15;
            default:
                return input; // Jika skala asal adalah Reamur
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new KonversiSuhuForm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

}
